<?php

/**
 * Cookie Consent Module
 *
 * @author    Peter McWilliams <pmcwilliams@augustash.com>
 * @copyright Copyright (c) 2022 August Ash (https://www.augustash.com)
 */

/** @var \Augustash\CookieConsent\Block\Banner $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->isEnabled()): ?>
    <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
    <script>
        <?php if ($block->hasTransition() === false): ?>
        window.cookieconsent.hasTransition = false;
        <?php endif; ?>
        window.cookieconsent.initialise({
            "palette": {
                "popup": {
                    "background": "<?= $escaper->escapeHtml($block->getBannerColor()) ?>",
                    "text": "<?= $escaper->escapeHtml($block->getBannerTextColor()) ?>"
                },
                "button": {
                    "background": "<?= $escaper->escapeHtml($block->getButtonColor()) ?>",
                    "text": "<?= $escaper->escapeHtml($block->getButtonTextColor()) ?>"
                }
            },
            "theme": "<?= $escaper->escapeHtmlAttr($block->getLayout()) ?>",
            "position": "<?= $escaper->escapeHtmlAttr($block->getPosition()) ?>",
            "type": "<?= $escaper->escapeHtmlAttr($block->getComplianceType()) ?>",
            "static": <?= $escaper->escapeHtmlAttr($block->isStatic()) ?>,
            "showLink": <?= $escaper->escapeHtmlAttr($block->showLink()) ?>,
            "content": {
                "dismiss": "<?= $escaper->escapeHtmlAttr($block->getButtonText()) ?>",
                <?php if ($block->getCmsUrl()): ?>
                "href": "<?= $escaper->escapeHtmlAttr($block->getCmsUrl()) ?>",
                <?php endif; ?>
                <?php if ($block->showLink() == 'true' && $block->getLinkText()): ?>
                "link": "<?= $escaper->escapeHtmlAttr($block->getLinkText()) ?>",
                <?php endif; ?>
                "message": "<?= $escaper->escapeHtmlAttr($block->getMessage()) ?>"
            },
            "cookie": {
                "name": "<?= $escaper->escapeHtmlAttr($block->getCookieName()) ?>",
                "path": "<?= $escaper->escapeHtmlAttr($block->getCookiePath()) ?>",
                "domain": "<?= $escaper->escapeHtmlAttr($block->getCookieDomain()) ?>",
                "expiry": <?= $escaper->escapeHtmlAttr($block->getCookieExpiry()) ?>,
                "secure": <?= $escaper->escapeHtmlAttr($block->isCookieSecure()) ?>
            }
        });
    </script>
<?php endif; ?>
